export const INFURA_GATEWAY: string = "https://thedial.infura-ipfs.io";
export const EMANCIPA_MARKET: `0x${string}` =
  "0xc088987ec832BEC8a33A10Bc5F7768D2240FBf34";
export const INFURA_GATEWAY_INTERNAL: string =
  "https://emancipa.xyz/api/infura/";

export const TOKENS: { symbol: string; contract: string; image: string }[] = [
  {
    symbol: "WGHO",
    contract: "0x6bDc36E20D267Ff0dd6097799f82e78907105e2F",
    image: "QmYCDxCv7mJyjn49n84kP6d3ADgGp422ukKzRyd2ZcGEsW",
  },
  {
    symbol: "WETH",
    contract: "0xE5ecd226b3032910CEaa43ba92EE8232f8237553",
    image: "QmYJ6cpGRgQAr2d5hJDJ9CaJukt2szcHc1AqFBy9m6knUw",
  },
  {
    symbol: "MONA",
    contract: "0x28547B5b6B405A1444A17694AC84aa2d6A03b3Bd",
    image: "QmZSDyGYYy9hn8RAUC1vZeZXC5y2H3YimzajJRngCTu5Fq",
  },
];

export const IMAGE_SET: {
  imagen: string;
  title: string;
  anchura: number;
  altura: number;
  alt: string;
  error: string;
}[] = [
  {
    imagen: "QmNrybajbY5LhWDTLsAk86PWgigHKdu8DdSoX8RmbbAq75",
    anchura: 3038,
    error: "",
    title: "We Will Not Be Banned",
    altura: 4696,
    alt: "Masked woman displayed on dystopian city billboard, defiant resistance message We will not be banned, cyberpunk street billboard",
  },
  {
    imagen: "QmPzEyn2KM21ZkTyFTZLn7oqahYuUoAz7UNW9fcBDNfzqD",
    anchura: 2698,
    error: "",
    title: "This Body Is Yours",
    altura: 5503,
    alt: "Masked figure staring into neon-lit ruins with 'This body is yours' manifesto, dissident urban portrait",
  },

  {
    imagen: "QmRt6dpmTD7Ps42u3fBH2trJM4giVURGsL8XwwgBJuMUVn",
    anchura: 1025,
    error: "",
    title: "Encrypted Warrior: Trans Signal",
    altura: 1025,
    alt: "Psychedelic warrior masked in neon spirals with Trans Women Are Women declaration, encrypted identity art",
  },
  {
    imagen: "QmeJXfTzbe8qquHW8yrFYSHMtAiMgLcaab6f5qNG6j5bzX",
    anchura: 1025,
    error: "",
    title: "Neon Spiral Resistance",
    altura: 1025,
    alt: "Psychedelic warrior masked in neon spirals with Trans Women Are Women declaration, encrypted identity art",
  },
  {
    imagen: "QmVbzcttHWyRzu8ef2tLWkzKhAaoAo2PZwoAy7qyZFxExe",
    anchura: 1025,
    error: "",
    title: "Cyber Spiral Sisterhood",
    altura: 1025,
    alt: "Psychedelic warrior masked in neon spirals with Trans Women Are Women declaration, encrypted identity art",
  },

  {
    imagen: "QmdayoVLF4z7F1zufPDusmFbHRSUbvGoZLB7hS9xznSdmR",
    anchura: 1025,
    error: "",
    title: "Masked in Light, Armed with Truth",
    altura: 1025,
    alt: "Psychedelic warrior masked in neon spirals with Trans Women Are Women declaration, encrypted identity art",
  },
  {
    imagen: "QmZk7DFZhz9Y2JrfKJmUEpMmk8tfGkeaAHGUjSA1Ysquhh",
    anchura: 1025,
    error: "",
    title: "Trans Transmission in Neon Flesh",
    altura: 1025,
    alt: "Psychedelic warrior masked in neon spirals with Trans Women Are Women declaration, encrypted identity art",
  },
  {
    imagen: "QmZvRmxFdKE3zvdky62aCK65MXFfEyvfLbX9gG8ivKebiM",
    anchura: 1025,
    error: "",
    title: "Codebound Sisterhood Sentinel",
    altura: 1025,
    alt: "Psychedelic warrior masked in neon spirals with Trans Women Are Women declaration, encrypted identity art",
  },

  {
    imagen: "QmNNS4wKZaXggt9K4Ww6RKzTpjHJLxS7Vr5LmNA5akeTJ1",
    anchura: 896,
    error: "",
    title: "March of the Masked: City in Revolt",
    altura: 1360,
    alt: "Masked insurgents marching through occupied city streets, multilingual banners of defiance, autonomous uprising captured",
  },
  {
    imagen: "QmfACvMJYvcSJVQ1UucePwk7axutYr35rEPr2j3gkhMMRK",
    anchura: 960,
    error: "",
    title: "Star of Defiance",
    altura: 1344,
    alt: "Back view of a cryptographic insurgent marked with a Star of David and fractured trust slogans, resistance portrait",
  },
  {
    imagen: "QmWavSbkzSVBBGdKwZBCUZ1WpTvgnxctXfULkiJ86F2QxU",
    anchura: 1035,
    error: "",
    title: "What’s a Woman? Echoes from the Void",
    altura: 1592,
    alt: "Neon billboard over dead city skyline asking What's a woman?, anonymous insurgency artwork",
  },
  {
    imagen: "QmcfkgsSw5AXDJg3gKJt2ArSBmpRo9LkDtN5jLGdES6VZT",
    anchura: 759,
    error: "",
    title: "Fall of the Encrypted",
    altura: 1886,
    alt: "Masked rebel falling through the ruins of a collapsing city, sky fractured with encrypted Arabic messages, dystopian artwork",
  },
  {
    imagen: "QmbwcPAd82MD6bZNA85grZngWCTdQn7anDDvwP6tEV4F47",
    anchura: 816,
    error: "",
    title: "Static Faces Against the Wall",
    altura: 1456,
    alt: "Fragmented faces broadcast from hacked televisions stacked against a crumbling neon wall",
  },
  {
    imagen: "QmRpq7CBQrhQuxgiy2i36XVzqRVcy8WeQBQW1Ap9B5McXn",
    anchura: 1473,
    error: "",
    title: "Library of Broken Machines",
    altura: 769,
    alt: "Underground sanctuary of books and broken systems lit by cracked computer screens",
  },

  {
    imagen: "QmTsYZYvc3ZBaSxXRuDywsUyBMUrXipNjBs3ySRBczL3qh",
    anchura: 1807,
    error: "",
    title: "Watcher in the Violet Circuit",
    altura: 943,
    alt: "Silent watcher perched above violet-lit skyscrapers scanning encrypted city signals",
  },
  {
    imagen: "QmaGDN8WD53y7SdwPmYwu6XTDsSSqg581DvTq6ucuiH2Xz",
    anchura: 1472,
    error: "",
    title: "Absolute Autonomy Rises",
    altura: 824,
    alt: "Masked figure painted on decaying high-rise proclaiming absolute autonomy",
  },
  {
    imagen: "QmYUgZKL6RqpsLnbxdd8CazVcNJE8KV73cGenzit6BcTzb",
    anchura: 817,
    error: "",
    title: "Shadow Siege: End of Ownership",
    altura: 1457,
    alt: "Shadow creatures loom over crumbling skyline as rebels tear down false ownership",
  },

  {
    imagen: "QmXSzv2WkgjzDbXUymnVkqeK45QKVNdSUhh5gX9yLspjFw",

    anchura: 754,
    error: "",
    title: "Ghost Codes on Broken Frequencies",
    altura: 1330,
    alt: "Masked drifter hacks lost communication channels with obsolete tech and ghost codes",
  },
  {
    imagen: "QmSgDkJADYRxtBGwVqe6krkQKez6UoCvEmGDVLwFrksxPn",

    anchura: 810,
    error: "",
    title: "Encrypted Revolts Across the Noise",
    altura: 1970,
    alt: "Masked voices ignite encrypted revolts across saturated megacities",
  },
  {
    imagen: "QmbPNx8mPKKPwt7YaDFZ9PUhag4g9eSP9wFNs4aCvEcFmj",

    anchura: 945,
    error: "",
    title: "Mechanic of the Wrecked Mindscape",
    altura: 1473,
    alt: "Blue-haired mechanic assembles tools of liberation from wrecked knowledge systems",
  },
  {
    imagen: "QmVE7pDrbBpB95bc8u3XaWEoLbzDbvtR7CRSKNFq3E2BeA",

    anchura: 1112,
    error: "",
    title: "Midnight March of the Unruled",
    altura: 1440,
    alt: "Masked insurgents flood midnight streets armed with raw independence manifestos",
  },
  {
    imagen: "QmbVKUSF2xLCfTd4fXVXw3SSX8hbxHBr6mP1YTUzPuaUQV",

    anchura: 1869,
    error: "",
    title: "Echoes from the Deleted Regime",
    altura: 1289,
    alt: "Distorted echoes ripple across encrypted memories of fallen regimes",
  },

  {
    imagen: "QmZS9LSB2L8vVULaZRGzEiXijdAMcFwHUzdfgMZxYnQam7",
    anchura: 922,
    error: "",
    title: "Six-String Firestarter",
    altura: 794,
    alt: "Guitarist ignites rebellion with every chord",
  },
  {
    imagen: "QmRthdHrbf2wBbV1huVqCAiAbCMmKJrYLqfNF6NEtfhpUi",
    anchura: 922,
    error: "",
    title: "Chord by Chord: Rebellion Riffs",
    altura: 794,
    alt: "Guitarist ignites rebellion with every chord",
  },
  {
    imagen: "QmVLmhzPcesBtbKERM5yGcZC6jZ4UgbLSWdDvE5DHLTKLJ",
    anchura: 922,
    error: "",
    title: "Strumming the Uprising",
    altura: 794,
    alt: "Guitarist ignites rebellion with every chord",
  },

  {
    imagen: "QmeXfAbhtx8jxA2RfP7d4XBdDvoR48ot2mXjiPQzQW6CAt",
    anchura: 922,
    error: "",
    title: "Rebel Sound, Electric Ground",
    altura: 794,
    alt: "Guitarist ignites rebellion with every chord",
  },
  {
    imagen: "QmWPdbKx7bfxYQSjFRceLnQz1utuhBGHD7pNb2QgRrP6cc",
    anchura: 922,
    error: "",
    title: "Guitarist in the Pulse War",
    altura: 794,
    alt: "Guitarist ignites rebellion with every chord",
  },
  {
    imagen: "Qmf65wCaJqUsFB44itaqHDikFtR9nBqNt8UJ7rr76UiRL8",
    anchura: 922,
    error: "",
    title: "Strings of Defiance",
    altura: 794,
    alt: "Guitarist ignites rebellion with every chord",
  },
  {
    imagen: "QmfXPtT1DZiHfCRhTcFaM94JzgFqP3GYFchfvePajSZ2td",

    anchura: 858,
    error: "",
    title: "Second Skin: Built to Break Chains",
    altura: 1282,
    alt: "Forge autonomy into your second skin",
  },
  {
    imagen: "QmPv1dUj5iT459mc4ADmTJRH8W8QDvtUUPWLqLmWwzhY4f",

    anchura: 1213,
    error: "",
    title: "Encrypted Fields Against Apartheid",
    altura: 1472,
    alt: "A field of encrypted dreams against apartheid",
  },
  {
    imagen: "QmaYPJRX1Dtose4njdsJ6vVgEfLHBydGWMvhonxUNVmwBe",

    anchura: 1456,
    error: "",
    title: "Walls That Remember",
    altura: 816,
    alt: "Silent city walls glowing with encrypted memories",
  },
  {
    imagen: "QmVwmNVU7WLz1bC1umLtTcyYoGBgDMBij3dVXu2GGSVFA3",

    anchura: 816,
    error: "",
    title: "Machines Ride into Tomorrow",
    altura: 1192,
    alt: "Riding machines into the dawn of dissidence",
  },
  {
    imagen: "QmaJZUQNBcMwrCsTpXR6HtC1gmgHvL34fUkbJuwzpBC2CE",

    anchura: 737,
    error: "",
    title: "Masked Vision Against Collapse",
    altura: 977,
    alt: "Masked gaze defying collapsing systems",
  },
  {
    imagen: "QmPbVz7oeNx2yL8Q436GSq3tXftR1Jc1fAAdmPv5pobLxy",

    anchura: 817,
    error: "",
    title: "Source Code and Fury",
    altura: 1457,
    alt: "Hacking the regime with open-source code and rage",
  },
  {
    imagen: "QmWAnqcp9ayYvb5NBPefpBrYa2fJWvyyZKdBZPZiUqQdby",

    anchura: 816,
    error: "",
    title: "Freedom Rewritten in Binary Tongues",
    altura: 1456,
    alt: "Reprogramming freedom in the language of machines",
  },
  {
    imagen: "QmXVWGfMA4w6M5c9BVUdEy6MCa2X5eXoPgX2vvth6dz2vX",

    anchura: 816,
    error: "",
    title: "Graffiti in the Aftermath",
    altura: 1456,
    alt: "Painted slogans blooming in the ruins of order",
  },
  {
    imagen: "QmRnjm5s4epfV6ryZGm4C7GgRPBB8Qc5qewgkkhgU6MACS",

    anchura: 1111,
    error: "",
    title: "Labyrinth Walker in the Ashes",
    altura: 1260,
    alt: "Woman cloaked in black navigates crumbling labyrinth",
  },
  {
    imagen: "QmXU1xLCg2A1MWn4Z2HGVpd2Eww216D3dNrnyWvMTeuK8A",

    anchura: 849,
    error: "",
    title: "Eyes Up, Systems Down",
    altura: 985,
    alt: "Masked woman glares defiantly under looming eyes",
  },
  {
    imagen: "QmZSS9ywhbUyZdZyQN9pm57PEzujG2LJXTrjqqnBtMy4mn",

    anchura: 817,
    error: "",
    title: "Uprising on Two Wheels",
    altura: 1458,
    alt: "Girl on bicycle reaches for giant butterfly in uprising",
  },
  {
    imagen: "QmZrJZiu2DLHYc2rFRgdSS3Dj4ooyARmwbxStU4hmZUrDS",

    anchura: 1457,
    error: "",
    title: "Flame Veil Against Control",
    altura: 817,
    alt: "Face of woman veiled in abstract flames, warning on Sharia law",
  },
  {
    imagen: "QmWurCyCPYjLsVCwPVDEr8X6dtR5CpGK4tAdADbDfTo98u",

    anchura: 561,
    error: "",
    title: "Fierce and Blonde Beneath the Banner",
    altura: 793,
    alt: "Masked blonde woman stands fierce under protest slogan",
  },
  {
    imagen: "QmeVWZWCBu1ESULm6mFv5uWoavEvgdYJ3HArRDT6GHi2oG",

    anchura: 1225,
    error: "",
    title: "Schoolyard Rebellion",
    altura: 1233,
    alt: "Schoolgirls raise middle fingers at authoritarian slogan",
  },
  {
    imagen: "QmXoYBSwUxHbpg8kNrUotvtEnKHXCn56yrHqgbbGJctBLZ",

    anchura: 817,
    error: "",
    title: "Unleashed Between Ruins",
    altura: 1457,
    alt: "Masked woman with wild hair rises between ruined buildings",
  },
  {
    imagen: "QmRt1U9B61YNnncn7u4vZEZjXo6EsWXJFpKWB18zrSNa6k",
    alt: "Retro cartoon woman eats cereal, urges gender equality.",
    anchura: 817,
    error: "",
    title: "Eat the Cereal, Smash the Norms",
    altura: 1457,
  },
  {
    imagen: "QmZkj8JKFWabdxXZUTCJRkatrZd2wMfHZaeCYypvvLqCjv",
    alt: "Rebel spirit stares through cracked reflections",
    anchura: 1457,
    error: "",
    title: "Shattered Mirror Stare",
    altura: 817,
  },
  {
    imagen: "QmWoLW6b6mcYY9xcThcPEoEgWCjLamGA4zvnQ3Go3WoNTd",
    alt: "Victory rises from the ruins of silence",
    anchura: 1457,
    error: "",
    title: "Victory Through Broken Silence",
    altura: 817,
  },
  {
    imagen: "QmPDJsMYwBspJ3AyvTJKoc7Ng9NiFDHE36GsR6f1dCpaiY",
    alt: "Freedom letters bleed through broken mirrors",
    anchura: 1457,
    error: "",
    title: "Letters in the Shards",
    altura: 817,
  },
  {
    imagen: "QmeEPEJzpQZwrFGVUau944AiNHJds8ALGTvzmB3Wq7vDe2",
    alt: "Masked runner charges into neon resistance",
    anchura: 931,
    error: "",
    title: "Run Toward the Neon Storm",
    altura: 1233,
  },
  {
    imagen: "QmYAHD8fBin4DM4QJP5ie4TGC7EQSd8qymApXas2guFWd7",
    alt: "Urban warrior outruns the erasers of memory",
    anchura: 769,
    error: "",
    title: "Erase Me If You Can",
    altura: 1537,
  },
  {
    imagen: "QmVg5Rh5dm2pzvxnZcDFSbZY719XismvbnV4E8et44qa5y",
    alt: "Paint-splattered revolt climbs toward clean skies",
    anchura: 768,
    error: "",
    title: "Paint Rebellion Into the Sky",
    altura: 1536,
  },
  {
    imagen: "QmVD9YZkQJqDjHZUkLSdDgeUKEQRLXsVdCuabq9vP6NuFL",
    alt: "Dockside dreamer plots escape beyond steel giants",
    anchura: 1457,
    error: "",
    title: "Escape Map Under the Cranes",
    altura: 817,
  },
  {
    imagen: "QmbuygbeEK5MimoNokmY5MozddUnV9VSA3awYisXPvaBxg",
    alt: "Code and myth entwine beneath hacked skylights",
    anchura: 689,
    error: "",
    title: "Skyline Mythbreaker",
    altura: 1729,
  },
  {
    imagen: "QmWAkeDcCRpYQqAWgqQf46m6uSRPdgTKJEQHTktJzfvL72",
    alt: "Girl faces a cosmic vortex, ready to tear open new worlds",
    anchura: 1457,
    error: "",
    title: "Vortex Calling the Brave",
    altura: 817,
  },
  {
    imagen: "QmdViyXtwRUJeDiykUYsLyGAQmDYejqhSLX3mDXNSLQ5DG",
    alt: "Masked woman glitches out of the neon skyline",
    anchura: 897,
    error: "",
    title: "Out of Sync, Out of Reach",
    altura: 1345,
  },
  {
    imagen: "Qmc9d941voNQ6a79Jk51bdzTvd5aFoyks4nsQfuA4jMyor",
    alt: "Rebel woman pierces the grid with electric defiance",
    anchura: 897,
    error: "",
    title: "Electric Gaze Through the Grid",
    altura: 1345,
  },
  {
    imagen: "QmVmo8enUp2ZdHs6YxsD8pBfeUfLUVreiGkKcCQMQpY2oj",
    alt: "Pink-haired girl stands over a suffocating concrete jungle",
    anchura: 897,
    error: "",
    title: "Pink Crown Above the Concrete Sea",
    altura: 1345,
  },
  {
    imagen: "QmXVmHhcidgwoLvREeuWmp5YvckTYDcbUYhk4M7aLzB6xJ",
    alt: "Dreamers burn bright above the sleeping city",
    anchura: 737,
    error: "",
    title: "City Sleeps, Dreamers Burn",
    altura: 1305,
  },
  {
    imagen: "QmUbQ8xEBerraUGwQPyakHstMoHNSXG4vm7jHhsPm2Gtqc",
    alt: "Masked girl reads red-hot news against a cracked wall",
    anchura: 816,
    error: "",
    title: "Bulletins From a Burning Wall",
    altura: 1456,
  },
  {
    imagen: "QmcciJCDSewwDfjYUV3XePW595CfYdANj9RB2XRkSiZjHf",
    alt: "Schoolgirl and deer meet under an 8-bit pastel sky",
    anchura: 897,
    error: "",
    title: "Glitched Pastel Encounter",
    altura: 1345,
  },
  {
    imagen: "QmTs7PYFmjaDppmAiq4CdrTJ31LADpbn4P82N2zPvtKvFV",
    alt: "Lone girl hikes under a fierce moon chasing city lights",
    anchura: 1457,
    error: "",
    title: "Girl Chasing Citylight Moons",
    altura: 816,
  },
  {
    imagen: "QmaJ3383VA9oywEdLT8GX6pEZJASTvrVysavkhdS8zVh5q",
    alt: "Girl climbs the black grass, pink moon calling her",
    anchura: 1457,
    error: "",
    title: "Pink Moon Beckons the Climber",
    altura: 816,
  },
  {
    imagen: "QmRcvQrRrYpdyq9UfehwoAobPXP2jaZZEiZu3Y57r2Qh4p",
    alt: "Girl stands before a blazing full moon over a sleeping city",
    anchura: 1457,
    error: "",
    title: "Full Moon, Silent Streets",
    altura: 816,
  },
  {
    imagen: "QmfTd3pN3FWiV6LMhJCt4dYVkC5q2AAbgQwqoaGMpaeqWK",
    alt: "Blue-haired girl decodes forbidden knowledge under a library’s skylight",
    anchura: 1097,
    error: "",
    title: "Skylight Secrets and Cyan Hair",
    altura: 1841,
  },
  {
    imagen: "QmNjKVnpi5UvrXxWocz8gMFXeLojj1FkwpcUUrAnb4iXni",
    alt: "Girl with silver hair dreams of escape under a giant full moon in a tower of books",
    anchura: 689,
    error: "",
    title: "Tower of Books and Moonlit Escape",
    altura: 1728,
  },
  {
    imagen: "QmVqM8YYRyna1Ns46hE2yhJU81W6usBWizGDp3yLPJu24f",
    alt: "Hacker girl tunes into static and starlight on a rooftop above neon streets",
    anchura: 1457,
    error: "",
    title: "Starlit Static Hacker",
    altura: 817,
  },
  {
    imagen: "QmZeQdvpAPs65ex5nzctZaSggGL66a4geY1jzQJWvPWznE",
    alt: "Mermaid waiting for a jailbreak she has to spark herself",
    anchura: 816,
    error: "",
    title: "Mermaid Jailbreak in Progress",
    altura: 1456,
  },
  {
    imagen: "Qmdymc6P52w2qysfwvuqckYko7Bk4vkUmmsDptyuvAYTwK",
    alt: "Dark-skinned girl in white face paint, fiery background, full moon above",
    anchura: 929,
    error: "",
    title: "Moonlit Fire Mask",
    altura: 1329,
  },
  {
    imagen: "QmUxiUrsQkkfUS9SfCGtGmAoTMXJw9qew9Az3du4BoCg8d",
    alt: "Silhouette of a girl walking toward a rising sun over a hill, dotted radiance exploding behind her",
    anchura: 944,
    error: "",
    title: "Sunrise Detonation Walker",
    altura: 1360,
  },
  {
    imagen: "QmXymTLZB4sG1NfbS3MEneSq3Be2GdfYf3EPgtEMKUVA9i",
    alt: "Women in traditional clothing, climbing sharp blue mountains with freedom flags, no roads, no maps",
    anchura: 816,
    error: "",
    title: "No Path, Only Ascent",
    altura: 1456,
  },
  {
    imagen: "QmZiaeWySygkeah5V7oawzLvQMmANLUG85tHqZ5292XwUD",
    alt: "Woman in racing gear, speeding on a track at sunset",
    anchura: 1025,
    error: "",
    title: "Speed Queen in Sunset Drift",
    altura: 1089,
  },
  {
    imagen: "QmbAau1GR3FQEPuanbv9ELXn9kkHxaiGbg8rXCnxGhnAw2",
    alt: "Pixel art of a red-haired girl with bat wings, white mask, against a sky backdrop",
    anchura: 1346,
    error: "",
    title: "Pixel-Winged Redhead in Flight",
    altura: 898,
  },
  {
    imagen: "QmeMYVoM2i9rUqYLDFZYXAUxuLdvAYzMgvGf366UK1Yi6E",
    alt: "Face of a woman split into colors, radiant patterns above her head, sovereign message",
    anchura: 945,
    error: "",
    title: "Split Face, Sovereign Code",
    altura: 1401,
  },
  {
    imagen: "QmTFPMf1mc1M5mEALsodGTNEitT9NLWWbQ7MUNVU2HZgWk",
    alt: "Flower-covered woman with red mask, looking to the side, delicate French text behind",
    anchura: 846,
    error: "",
    title: "Masked in Flowers, Whispering in French",
    altura: 1676,
  },
  {
    imagen: "QmNZqXS6vhTcYjbRHg4MAAqeGLtHVcr4AipDsjCqxDjQZZ",
    alt: "Flower-covered woman with red mask, with Japanese script, staring forward",
    anchura: 847,
    error: "",
    title: "Floral Face, Eyes Forward in Kanji",
    altura: 1677,
  },
  {
    imagen: "QmQ3nAvNMUjYg15YNan7Ecs6iDjkR5sLzLTU8ncFGQ7osf",
    alt: "Black woman with yellow mask under a full moon, cosmic and proud",
    anchura: 898,
    error: "",
    title: "Moon-Crowned and Untamed",
    altura: 1345,
  },
  {
    imagen: "QmPTGFEZYmKy3jtC4ZUnSjjH2ouPsCbcEaHpQmWnikNGTT",
    alt: "Red lips float under a dead lamp in a midnight dive bar",
    anchura: 897,
    error: "",
    title: "Lips Under Neon’s Judgement",
    altura: 1345,
  },
  {
    imagen: "QmafePxPpnYXeJKjQS5hxSH7h6hDYzmeawjbxbEgGZmkP5",
    alt: "Sun with cracked lips spits rebellion over broken skies",
    anchura: 897,
    error: "",
    title: "Cracked Sun Screams Revolt",
    altura: 1345,
  },
  {
    imagen: "QmcGjT1Z4ZLg1oN6WkRPfQQSmanVRaBismgKDc1e4d6X7p",
    alt: "Neon-masked girl slices invisible strings in a hacked-out city",
    anchura: 1026,
    error: "",
    title: "Invisible Strings, Visible War",
    altura: 1026,
  },
  {
    imagen: "QmRLBkssHnauAJsHBC4edS9PvNcnWPVdBzgpzoYQbmEJUj",
    alt: "Red-masked woman blows bubblegum under freedom’s broken gaze",
    anchura: 1026,
    error: "",
    title: "Bubblegum Rebellion Under Surveillance",
    altura: 1538,
  },
  {
    imagen: "QmTXt3wbPLqBA8HCHF6J1PrZ3wLw6BAYqahprBpFbL5LZ6",
    alt: "Pixelated faces glitch behind the cold scream of NO in electric night",
    anchura: 1025,
    error: "",
    title: "Pixelated NO, Electric Night",
    altura: 1025,
  },
  {
    imagen: "QmP32YWzGAs2Fy3bDCjXAUbvkSCqsdvLGR42EHkfgDtRZp",
    alt: "Five mouths scream identity in a neon-blasted void",
    anchura: 1025,
    error: "",
    title: "Five Mouths, One Void",
    altura: 1537,
  },
  {
    imagen: "QmYXaX5XxLZjNbhZpHWiWB4QVqiee982UC5ZpxNMV9RJ7Z",
    anchura: 1026,
    error: "",
    title: "Queen of Goldfire Collapse",
    altura: 1538,
    alt: "Masked queen burns gold fire straight into a collapsing horizon",
  },
  {
    imagen: "QmfSbGMcaY81hRU2NhL5eDkAWEjbeaz1GfwUKpwcXG6xxe",
    anchura: 1026,
    error: "",
    title: "Jaguar Scarred, Neon-Bound",
    altura: 1538,
    alt: "Bubblegum queen with jaguar scars stares down a neon jungle",
  },
  {
    imagen: "Qmf7f1hyFyaz741SsDGiUwqdYu4tPNLHfvFeWcQ128M1sX",
    anchura: 1025,
    error: "",
    title: "Skater Flame in Sunset Silence",
    altura: 1537,
    alt: "Red-masked skater girl walks through sunset winds like a loaded question",
  },
  {
    imagen: "QmbVrDxgGL35JHhtWZG2NXV4YAV4ewRncVU8LbNzVTfBws",
    anchura: 818,
    error: "",
    title: "Neon Moon, Green-Haired Loner",
    altura: 1458,
    alt: "Lone green-haired girl stands between dying towers and a swirling neon moon",
  },
  {
    imagen: "QmSF2rJ73nTnAZGFgB2QHJjpipDgkSvyxG4rFrtukaE3Dx",
    anchura: 1025,
    error: "",
    title: "Fantasma 1: Own It, Don’t Pray for It",
    altura: 1542,
    alt: "Fantasma 1. Own your life, don't borrow it from some deity.",
  },
  {
    imagen: "QmUkwzWc273cic1u7awTL8b1MEBL4CZF8SxceFDzb5PLJQ",
    anchura: 1025,
    error: "",
    title: "Fantasma 2: No Gods, Just Ownership",
    altura: 1537,
    alt: "Fantasma 2. Own your life, don't borrow it from some deity.",
  },
  {
    imagen: "QmcumXniwDPsQKQzS7ssY6bMYXXGJYg7orv9VUwPvoBT5r",
    anchura: 961,
    error: "",
    title: "Cliffside Ghost in Self-Reconstruction",
    altura: 1601,
    alt: "Recompose who I am. Glowing fantasma on the cliff's edge.",
  },
];
